# Writes src/tray/world_map.gen.h: the main screen's world map (world_map.h)
# from Natural Earth (public domain) - the land as dots on a 1-degree grid,
# and each country's capital, for the route from the user's country to the
# exit's. Run again only to change the data; the header is committed.
#
#   pwsh tools/worldmap/generate.ps1        (or Windows PowerShell 5.1)
#
# The sources are pinned (v5.1.2) and fetched through jsdelivr's mirror of
# github.com/nvkelso/natural-earth-vector.

param([string]$Out = (Join-Path $PSScriptRoot '..\..\src\tray\world_map.gen.h'))
$ErrorActionPreference = 'Stop'

$base = 'https://cdn.jsdelivr.net/gh/nvkelso/natural-earth-vector@v5.1.2/geojson'
$work = Join-Path ([IO.Path]::GetTempPath()) 'sovereign-worldmap'
New-Item -ItemType Directory -Force $work | Out-Null
foreach ($name in 'ne_110m_land.geojson', 'ne_110m_populated_places_simple.geojson') {
  $path = Join-Path $work $name
  if (-not (Test-Path $path)) {
    curl.exe -fsSL --retry 3 -o $path "$base/$name"
    if ($LASTEXITCODE -ne 0) { throw "download of $name failed" }
  }
}

Add-Type -Language CSharp -TypeDefinition @'
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text.RegularExpressions;

public static class WorldMapGen {
  // Every ring of every land polygon: [lon, lat] pairs. Even-odd over all of
  // them counts holes (lakes) right.
  public static List<double[]> Rings(string geojson) {
    var rings = new List<double[]>();
    // A ring is a run of [x, y] pairs between "[[" and "]]".
    foreach (Match ring in Regex.Matches(geojson, @"\[\s*(\[\s*-?[\d.eE+-]+\s*,\s*-?[\d.eE+-]+\s*\]\s*,?\s*)+\]")) {
      var points = new List<double>();
      foreach (Match p in Regex.Matches(ring.Value, @"\[\s*(-?[\d.eE+-]+)\s*,\s*(-?[\d.eE+-]+)\s*\]")) {
        points.Add(double.Parse(p.Groups[1].Value, CultureInfo.InvariantCulture));
        points.Add(double.Parse(p.Groups[2].Value, CultureInfo.InvariantCulture));
      }
      if (points.Count >= 6) rings.Add(points.ToArray());
    }
    return rings;
  }

  public static bool Inside(List<double[]> rings, double lon, double lat) {
    bool inside = false;
    foreach (var r in rings) {
      int n = r.Length / 2;
      for (int i = 0, j = n - 1; i < n; j = i++) {
        double xi = r[2 * i], yi = r[2 * i + 1], xj = r[2 * j], yj = r[2 * j + 1];
        if ((yi > lat) != (yj > lat) && lon < (xj - xi) * (lat - yi) / (yj - yi) + xi) inside = !inside;
      }
    }
    return inside;
  }
}
'@

$land = [WorldMapGen]::Rings([IO.File]::ReadAllText((Join-Path $work 'ne_110m_land.geojson')))
$dots = New-Object System.Collections.Generic.List[string]
for ($lat = -58; $lat -le 80; $lat += 1) {
  for ($lon = -180; $lon -le 179; $lon += 1) {
    if ([WorldMapGen]::Inside($land, $lon, $lat)) { $dots.Add("{$lat, $lon}") }
  }
}

# The coastlines: every ring of the land, in tenths of a degree, one after
# another; kCoastStarts says where each begins.
$coast = New-Object System.Collections.Generic.List[string]
$starts = New-Object System.Collections.Generic.List[string]
foreach ($ring in $land) {
  $starts.Add([string]$coast.Count)
  for ($i = 0; $i -lt $ring.Length; $i += 2) {
    $coast.Add(('{{{0}, {1}}}' -f [int][math]::Round($ring[$i + 1] * 10), [int][math]::Round($ring[$i] * 10)))
  }
}

$places = [IO.File]::ReadAllText((Join-Path $work 'ne_110m_populated_places_simple.geojson')) | ConvertFrom-Json
$capitals = [ordered]@{}
foreach ($f in $places.features) {
  $p = $f.properties
  if ($p.featurecla -notmatch 'Admin-0 capital' -or $p.iso_a2 -notmatch '^[A-Z]{2}$' -or $capitals.Contains($p.iso_a2)) { continue }
  $capitals[$p.iso_a2] = '{{"{0}", {1}f, {2}f}}' -f $p.iso_a2, ([double]$p.latitude).ToString('0.00', [Globalization.CultureInfo]::InvariantCulture), ([double]$p.longitude).ToString('0.00', [Globalization.CultureInfo]::InvariantCulture)
}
$capitalLines = ($capitals.Keys | Sort-Object | ForEach-Object { $capitals[$_] }) -join ",`n    "

$text = @"
// Generated by tools/worldmap/generate.ps1 - do not edit. Made with Natural
// Earth (public domain): ne_110m_land, ne_110m_populated_places_simple v5.1.2.
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace sovereign::tray::world {

// A point of land: latitude and longitude, degrees, on a 1-degree grid.
struct LandDot {
  std::int8_t lat;
  std::int16_t lon;
};

inline constexpr std::array<LandDot, $($dots.Count)> kLand = {{
    $(($dots -join ', '))
}};

// The coastlines: the land's rings, a point after another in tenths of a
// degree (latitude, longitude); each ring from its start to the next one's.
struct CoastPoint {
  std::int16_t lat;
  std::int16_t lon;
};

inline constexpr std::array<CoastPoint, $($coast.Count)> kCoast = {{
    $(($coast -join ', '))
}};

inline constexpr std::array<std::uint16_t, $($starts.Count)> kCoastStarts = {{
    $(($starts -join ', '))
}};

// A country's capital: ISO 3166-1 alpha-2, latitude, longitude.
struct Capital {
  std::string_view country;
  float lat;
  float lon;
};

inline constexpr std::array<Capital, $($capitals.Count)> kCapitals = {{
    $capitalLines
}};

}  // namespace sovereign::tray::world
"@
[IO.File]::WriteAllText((Resolve-Path (Split-Path $Out)).Path + '\' + (Split-Path $Out -Leaf), $text.Replace("`r`n", "`n"), (New-Object Text.UTF8Encoding $false))
"world_map.gen.h: $($dots.Count) land dots, $($coast.Count) coast points in $($starts.Count) rings, $($capitals.Count) capitals"
